openapi: 3.1.0
info:
  title: Token API
  description: "The API is used by the consumer of the API to get account information and reporting of global, multi-country Account statement and Debit/Credit entries. At any time during the operating hours of the system, the account owner can request to get information about the account(s) that the account servicer maintains for the member. For example, this may be necessary in order to perform the appropriate liquidity management and the funds transfers between accounts. The API currently supports endpoint to get entries reported to the account, and/or to provide the owner with balance information on the account at a given point in time.\n\n`The API supports following functionalities:`\n\n* Retrieve list of account with balance information\n* Retrieve details of a specific account\n* Retrieve debit/credit entries reported to the account pending and booked items on the account at a given point in time to enable intraday reconciliation\n* Get account statement by the account owner, or authorised party, of the entries booked to the account, and to provide the owner with balance information on the account at a given point in time\n\n`Error Responses`\n\nThe API uses common HTTP status codes in the response header to indicate success or failure. Specific error code and description will be returned in the custom error schema.\n\n`Query Parameters`\n\nEach URL query parameter specifies an API query parameter that must be URL encoded.\n\n**v1.0.9 Release Notes**\n* All schema object containing \"oneOf\" syntax is updated to align with open API specification.\n* The header parameter X-ServiceProvider will be changed to X-UserContext.\n* PostalAddressUnstructured.country has been changed to optional.\n* An element CashAccount41.alternate_identification is added as a resource identifier where account identification cannot be used as a resource identification.\n* The element CashAccount41.linked_account  is changed to CashAccount41.related_account.\n* The elements CashCurrentBalance1.balance_type, CashAvailableBalance1.balance_type, CashForwardAvailableBalance1.balance_type has been dropped.\n* Batch indicator block to statement lines is added.\n* Return information block is added to Statement.\n* The charges block is added to Statement Entry details level.\n* The size of the element \"identification\" in both Statements and Statement Lines has been increased to 36 from 35 to accommodate UUID.\n\n**v1.0.8 Release Notes**\n* The query parameter account-servicer is added to the getAccounts endpoint.\n* Party identification object (Organisation/Person) in Statements and Statement Lines is changed to ISO component style. This is to address use case where identification of object is not always possible when only party name is available.\n* Account Identification in Statements and Statement Lines is aligned with ISO component.\n* Remittance Information, Purpose and Bank Transaction Code is added to Statement Lines.\n* The element interest, related_account is added to Statements    \n"
  contact:
    name: Standards & Developer Hub
    url: https://developer.swift.com
    email: developer-support@swift.com
  version: "1.0.9"
  x-server-configuration:
    default-environment: Authorization
    default-server: Sandbox Server
    environments:
      - name: Authorization
        servers:
          - name: Sandbox Server
            url: https://sandbox.swift.com/oauth2/v1
          - name: Pilot Server
            url: https://api-test.swiftnet.sipn.swift.com/oauth2/v1
          - name: Live Server
            url: https://api.swiftnet.sipn.swift.com/oauth2/v1
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
servers:
  - url: https://sandbox.swift.com/oauth2/v1
    description: URL for obtaining OAuth2 token.
    variables: {}
  - url: https://api-test.swiftnet.sipn.swift.com/oauth2/v1
    description: URL for obtaining OAuth2 token.
    variables: {}
  - url: https://api.swiftnet.sipn.swift.com/oauth2/v1
    description: URL for obtaining OAuth2 token.
    variables: {}
paths:
  /token:
    post:
      tags:
        - Authorization
      summary: Request OAuth2 token
      description: Obtain an OAuth2 token using JWT bearer assertion and Basic Auth
      operationId: getToken
      security:
        - basicAuth: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  example: urn:ietf:params:oauth:grant-type:jwt-bearer
                assertion:
                  type: string
                  description: The JWT bearer assertion (auto-generated in Pre-request script)
                  example: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1YyI6WyJNSUlEcVRDQ0FwR2dBd0lCQWdJVWZJMThoNURrcS9XejZKZ1dXUmtYZzMrMkEvRXdEUVlKS29aSWh2Y05BUUVMQlFBd1pERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXVNUTB3Q3dZRFZRUUtEQVJFWlcxdk1TUXdJZ1lEVlFRRERCdGtaVzF2TFhOM2FXWjBMWE5oYm1SaWIzZ3RZMjl1YzNWdFpYSXdIaGNOTWpReE1EQTVNVFl3T0RNd1doY05NelF4TURBM01UWXdPRE13V2pCa01Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhEVEFMQmdOVkJBb01CRVJsYlc4eEpEQWlCZ05WQkFNTUcyUmxiVzh0YzNkcFpuUXRjMkZ1WkdKdmVDMWpiMjV6ZFcxbGNqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1JeWd5MkhaTm0rU2lSODJWRjdvd1Y0ZFhqUUdGOUk3V05yZHdYZXFwdkxZNU1WcGg0QlZpN2RObEJrRkxWOGxFckdBblR1d2plVnRlZklmTUxPTllXTVJUOC9wcG5nanVkQVZzc2s1M3EzbmlUQWpKM0plTVFkQkQ1WlcrZTl5UGtsWGgyMHdpcFlPVTlIT09pTTVKcDd0dTdJUHlOS1VtYkZMbDNLc2o0dzRVbkZYYXZNUnR1Zzg1dWtBQVYvNnozZmVUb3BVYTBxamdWcjdkUmthaHdmK1lZZ2JWTC9aZWFGc3RRRmZsSUFQekZGSWFteWNVNWE3eFNTcU9BZjRaemtaRllDWk9SY0tXZkRCMTJGRmFpQllkYldxY2ZnR1JLbnFVSXlGbjVsd3ZzR1cyQy9RcEVPZ2JjNVQ2Yyt5d08ybXRDaTRyY2dFMUNHWllLejVMRUNBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGTVBDMEkrVzFBNmxraU9VSnM5TVdET2ZHOE9GTUI4R0ExVWRJd1FZTUJhQUZNUEMwSStXMUE2bGtpT1VKczlNV0RPZkc4T0ZNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ3dLb2k2WXNDRjBYbnI0c0k4OVlFOVNxVjN6YU1YVitlNE5FekV6eURMZXY4d0p0MEt4ZEwyRDREQlVWam5OWkUvaFJXMHZkNlhUdzJTYnNXSmEzdjFpTkZLY2JpTlZqMU1pZ0NWcm1oZHFvNTVaZmFwRVp5SVpWNGdPOUN0RWFQcEtDOEZIM003VDFrYzljTC8yZGo5Z1psN3JScVZRVE1NM1FDNzJXdWpLV0I0WUNUaXBmWFphQlJxaEpsYmNZSGtkeE5nNDRjalNIOVAzRDV0RkdTa0ZBbW5EVUlzUEtXZXhxOCtiS0dpY2lzNWtyMDE0ZWVFSGtvMnFEbFBYYkppb0xRUDh6dXJzNWNuTElabkJlaklQWkEwVmFhM1dmSlhvVVkxdzFmVVdSb1hydCtUdjBta2owRE1HSUk5bzlkcG53MkpEckR3bWRYeHVZZEJyU0UwPSJdfQ.eyJpc3MiOiJhZHNhZGFkYSIsImF1ZCI6InNhbmRib3guc3dpZnQuY29tL29hdXRoMi92MS90b2tlbiIsInN1YiI6IkNOPWRlbW8tc3dpZnQtc2FuZGJveC1jb25zdW1lciwgTz1EZW1vLCBMPUxvbmRvbiwgUz1Mb25kb24sIEM9R0IiLCJqdGkiOiJORVVaOW4ydUNteHFzOVhqUC1Nc28iLCJleHAiOjE3MzgyNDY1MDgsImlhdCI6MTczODI0NTYwMywibmJmIjoxNzM4MjQ1NjAzfQ.RbKm7nTcaenElv8YMJCMoeWtqcsf7fwnOKj18Wz4AOTYsxMZP9E2i_jfpEF_1H5JRAmAKTT7moD30FuP0P_YNtCJ-teQ_Giyujfj3sHbUcuEIA7YXOabvKa2RDq2HOnGpSL68GUUNdxrMaI_QivQ1iGckkjWBYKlxkB3lLHNepMDy35h25AdslYXdnRHXGxIjougFXxLfwkHyspSUJAQB-4hN3m7HkPbr91TwPOzUlO96tMRWh1j072X-CGz2_8LS0cYhXfR8X7bb8TZdv1WkTgW0_elMY4dkwwvDvTEziUBraxgO6EW_5GjwGsUg0Thtlp8CHoiwk-6TAeoJoofwA
                scope:
                  type: string
                  example: swift.apitracker
              required:
                - grant_type
                - assertion
                - scope
      servers:
        authorization:
          url: https://sandbox.swift.com/oauth2/v1

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
tags:
  - name: Authorization
